### ISSUE TITLE
Apply the similar design to DOM API

### ISSUE THREAD

**Issue by hy9be** [kripken/webgl-worker#4]
Hi! I am thinking about doing the similar work for DOM APIs. Basically proxy the DOM calls so that some rendering logic can be moved to worker thread. Do you think it will be feasible? Any suggestions? Thanks!

**Comment by kripken** [comment]
It might work, but the biggest problem could be synchronous DOM calls, since the proxying is async. Another issue is that you need to have local caching of the DOM in the worker, and I'm not familiar enough with the DOM API to tell if that would work well - it happens to work well for OpenGL, which is not a coincidence as it's kind of intended to work that way.

**Comment by hy9be** [comment]
Got it. Thanks! I will give it a try.
